window.MILLIONPROJECT_RUNTIME_VERSION='runtime-31-interactions';
(()=>{
  if(window.__MP_RUNTIME31)return; window.__MP_RUNTIME31=true;
  const css=`html{scroll-behavior:auto!important}body.mp31-busy{cursor:progress}.mp31-toast{position:fixed;top:18px;right:18px;z-index:200200;background:#065f46;color:#fff;padding:10px 13px;border-radius:13px;font-weight:850;box-shadow:0 14px 36px rgba(15,23,42,.2)}.mp31-toast.bad{background:#991b1b}#mp31-quick{position:fixed;inset:0;z-index:200100;background:rgba(15,23,42,.38);display:grid;place-items:center;padding:14px;overscroll-behavior:contain}#mp31-quick .panel{width:min(680px,100%);max-height:88dvh;overflow:auto;background:#fff;border:1px solid #e5e7eb;border-radius:22px;padding:16px;box-shadow:0 26px 70px rgba(15,23,42,.24)}.mp31-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.mp31-head h3{margin:3px 0}.mp31-close{border:1px solid #e5e7eb;background:#fff;border-radius:11px;padding:8px 10px;font-weight:800}.mp31-tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:12px 0}.mp31-tabs button{border:1px solid #e5e7eb;background:#f8fafc;border-radius:12px;padding:10px 6px;font-weight:850}.mp31-tabs button.active{background:#111827;color:#fff;border-color:#111827}.mp31-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.mp31-f label{display:block;font-size:10px;color:#64748b;font-weight:850;margin-bottom:5px}.mp31-f input,.mp31-f select{width:100%;min-height:44px;border:1px solid #dfe4ec;border-radius:12px;background:#fff;padding:10px 11px;font-size:16px}.mp31-save{width:100%;margin-top:11px;border:0;border-radius:13px;background:#111827;color:#fff;padding:13px;font-weight:900}.mp31-short{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px;padding-top:12px;border-top:1px solid #edf0f4}.mp31-short button{border:1px solid #e5e7eb;background:#fff;border-radius:13px;padding:11px;text-align:left;font-weight:850}.mp31-short small{display:block;color:#7b8494;font-size:9px;margin-top:2px;font-weight:650}@media(max-width:700px){#mp31-quick{place-items:end center;padding:8px}#mp31-quick .panel{border-radius:22px 22px 13px 13px;max-height:89dvh;padding:14px}.mp31-grid{grid-template-columns:1fr}.mp31-short{grid-template-columns:1fr 1fr}}`;
  if(!document.getElementById('mp31-style')){const s=document.createElement('style');s.id='mp31-style';s.textContent=css;document.head.appendChild(s)}
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const cur=()=>{try{return tab||'o'}catch{return'o'}};
  const monthNow=()=>{try{return (typeof selectedMonth==='function'?selectedMonth():new Date().toISOString().slice(0,7)).slice(0,7)}catch{return new Date().toISOString().slice(0,7)}};
  const cats={expense:['餐飲／交通／日常','娛樂／治裝彈性','房租／住宿','父母／家庭支持','電信／網路','健身／健康','其他支出'],income:['獎金','兼職／其他收入','退款／回饋','其他收入'],saving:['緊急預備金','一般存款','旅遊基金','其他存款']};
  let qt='expense',pref={},navBusy=false,saveBusy=false;const scrolls={};
  const toast=(msg,bad=false)=>{document.querySelector('.mp31-toast')?.remove();const e=document.createElement('div');e.className='mp31-toast'+(bad?' bad':'');e.textContent=msg;document.body.appendChild(e);setTimeout(()=>e.remove(),2000)};
  try{const oldQ=(typeof q==='function'?q:null);if(oldQ&&!oldQ.__mp31){const cache=new Map();const cq=async function(t,o={}){const key=t+'|'+JSON.stringify(o||{}),now=performance.now(),hit=cache.get(key);if(hit&&now-hit.t<250)return hit.p;const p=Promise.resolve(oldQ(t,o));cache.set(key,{t:now,p});setTimeout(()=>{if(cache.get(key)?.p===p)cache.delete(key)},300);return p};cq.__mp31=true;window.q=cq;try{q=cq}catch{}}}catch(e){console.warn('mp31 q cache',e)}
  function syncActive(){const t=cur();document.querySelectorAll('[data-s28],[data-mp30]').forEach(b=>{const k=b.dataset.s28||b.dataset.mp30;b.classList.toggle('active',k===t||(k==='more'&&['r','d','l','s'].includes(t)))})}
  window.mp31Go=async k=>{if(navBusy)return;if(k===cur()){syncActive();return}const from=cur();scrolls[from]=window.scrollY||0;navBusy=true;document.body.classList.add('mp31-busy');try{try{tab=k}catch{window.tab=k}syncActive();if(typeof render==='function')await render();requestAnimationFrame(()=>window.scrollTo({top:scrolls[k]||0,left:0,behavior:'auto'}))}catch(e){console.error('mp31 navigation',e)}finally{syncActive();document.body.classList.remove('mp31-busy');navBusy=false}};
  window.mpGo=window.mp31Go;window.mpShellGo=window.mp31Go;
  window.mp31Close=()=>document.getElementById('mp31-quick')?.remove();
  const opts=(t,sel='')=>(cats[t]||[]).map(x=>`<option ${x===sel?'selected':''}>${esc(x)}</option>`).join('');
  async function fillCards(){try{if(typeof c==='undefined'||typeof u==='undefined'||!c||!u)return;const {data}=await c.from('credit_cards').select('issuer,card_name,status').eq('user_id',u.id).order('created_at');const s=document.getElementById('mp31-pay');if(!s)return;const vals=['銀行轉帳／現金',...(data||[]).filter(x=>x.status!=='inactive').map(x=>x.card_name||x.issuer),'其他'];s.innerHTML=[...new Set(vals.filter(Boolean))].map(x=>`<option>${esc(x)}</option>`).join('')}catch(e){console.warn('mp31 cards',e)}}
  window.mp31Type=t=>{qt=t;document.querySelectorAll('.mp31-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.t===t));const cat=document.getElementById('mp31-cat');if(cat)cat.innerHTML=opts(t,pref.category||'');const pw=document.getElementById('mp31-pay-wrap');if(pw)pw.style.display=t==='expense'?'block':'none'};
  window.mp31Quick=(type='expense',p={})=>{window.mp31Close();qt=['expense','income','saving'].includes(type)?type:'expense';pref=p||{};const m=monthNow(),today=new Date().toISOString().slice(0,10),date=today.slice(0,7)===m?today:m+'-01';const e=document.createElement('div');e.id='mp31-quick';e.onclick=x=>{if(x.target===e)window.mp31Close()};e.innerHTML=`<div class="panel"><div class="mp31-head"><div><div class="section-kicker">QUICK ACTION CENTER</div><h3>＋ 快速記錄</h3><div class="tiny">${esc(m)} · 立即開啟，不切換頁面</div></div><button type="button" class="mp31-close" onclick="mp31Close()">關閉</button></div><div class="mp31-tabs"><button type="button" data-t="expense" class="${qt==='expense'?'active':''}" onclick="mp31Type('expense')">支出</button><button type="button" data-t="income" class="${qt==='income'?'active':''}" onclick="mp31Type('income')">其他收入</button><button type="button" data-t="saving" class="${qt==='saving'?'active':''}" onclick="mp31Type('saving')">存款</button></div><div class="mp31-grid"><div class="mp31-f"><label>日期</label><input id="mp31-date" type="date" value="${esc(p.date||date)}"></div><div class="mp31-f"><label>用途</label><select id="mp31-cat">${opts(qt,p.category||'')}</select></div><div class="mp31-f"><label>金額</label><input id="mp31-amt" type="number" inputmode="decimal" min="0" value="${esc(p.amount||'')}" placeholder="0"></div><div class="mp31-f" id="mp31-pay-wrap" style="${qt==='expense'?'':'display:none'}"><label>付款方式</label><select id="mp31-pay"><option>銀行轉帳／現金</option><option>讀取信用卡中…</option></select></div></div><div class="mp31-f" style="margin-top:9px"><label>備註（可留白）</label><input id="mp31-note" value="${esc(p.note||'')}"></div><button type="button" class="mp31-save" onclick="mp31Save()">儲存這筆紀錄</button><div class="mp31-short"><button type="button" onclick="mp31Close();mp31Go('p').then(()=>setTimeout(()=>{try{openInvestmentBuy?.()}catch{}},70))">📈 記錄投資<small>同步持倉與成本</small></button><button type="button" onclick="mp31Close();mp31Go('p').then(()=>setTimeout(()=>{try{mpAddPlan?.()}catch{}},70))">↻ 定期定額<small>新增／管理計畫</small></button><button type="button" onclick="mp31Close();mp31Go('m').then(()=>setTimeout(()=>{try{mpLifeFixedSheet?.()}catch{}},90))">✓ 固定責任<small>查看本月待付款</small></button></div></div>`;document.body.appendChild(e);setTimeout(()=>document.getElementById('mp31-amt')?.focus(),30);fillCards()};
  window.mpQuickOpen=(type='expense',p={})=>window.mp31Quick(type,p);window.mpShellQuick=()=>window.mp31Quick('expense');window.mp28Quick=window.mp31Quick;window.mp26Quick=window.mp31Quick;
  window.mp31Save=async()=>{if(saveBusy)return;try{if(typeof c==='undefined'||typeof u==='undefined'||!c||!u)return toast('請先登入',true);const date=document.getElementById('mp31-date')?.value,amount=+(document.getElementById('mp31-amt')?.value||0),category=document.getElementById('mp31-cat')?.value||'其他',payment=qt==='expense'?(document.getElementById('mp31-pay')?.value||'銀行轉帳／現金'):'銀行轉帳／現金',note=(document.getElementById('mp31-note')?.value||'').trim();if(!date||!(amount>0))return toast('請輸入日期與金額',true);saveBusy=true;const m=date.slice(0,7),tag=pref.fixedKey?`[LIFE_FIXED:${pref.fixedKey}] `:'';const {error}=await c.from('finance_entries').insert({user_id:u.id,entry_date:date,month:m+'-01',entry_type:qt,category,amount,payment_method:payment,note:(tag+note).trim(),updated_at:new Date().toISOString()});if(error)throw error;window.mp31Close();toast('已記錄並同步');if(typeof render==='function')await render()}catch(e){toast('儲存失敗：'+(e?.message||''),true)}finally{saveBusy=false}};
  document.addEventListener('click',ev=>{const t=ev.target?.closest?.('button');if(!t)return;const quick=t.matches('.mp-s28-quick,#mp-shell28-fab,.mp-s28-actions .mainx,#mp30-fab,.mp30-qbtn')||String(t.textContent||'').trim().startsWith('＋ 快速操作');if(quick){ev.preventDefault();ev.stopImmediatePropagation();window.mp31Quick('expense');return}const k=t.dataset?.s28||t.dataset?.mp30;if(k&&k!=='more'){ev.preventDefault();ev.stopImmediatePropagation();window.mp31Go(k)}},true);
  ['mp26-side','mp26-bottom','mp26-fab','mp-shell27-side','mp-shell27-mobile','mp-shell27-fab'].forEach(id=>document.getElementById(id)?.remove());syncActive();
})();
