create table if not exists public.investment_plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  name text,
  monthly_amount numeric not null check (monthly_amount > 0),
  execution_day integer not null default 10 check (execution_day between 1 and 28),
  start_month date not null,
  end_month date,
  strategy text not null default '定期定額',
  status text not null default 'active' check (status in ('active','paused','ended')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (date_trunc('month', start_month)::date = start_month),
  check (end_month is null or date_trunc('month', end_month)::date = end_month),
  check (end_month is null or end_month >= start_month)
);

create index if not exists investment_plans_user_status_idx on public.investment_plans(user_id, status);
create index if not exists investment_plans_user_start_idx on public.investment_plans(user_id, start_month);

alter table public.investment_plans enable row level security;

drop policy if exists investment_plans_select_own on public.investment_plans;
create policy investment_plans_select_own on public.investment_plans for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists investment_plans_insert_own on public.investment_plans;
create policy investment_plans_insert_own on public.investment_plans for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists investment_plans_update_own on public.investment_plans;
create policy investment_plans_update_own on public.investment_plans for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists investment_plans_delete_own on public.investment_plans;
create policy investment_plans_delete_own on public.investment_plans for delete to authenticated using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.investment_plans to authenticated;
grant usage, select on all sequences in schema public to authenticated;
