create table if not exists public.app_versions (
  id bigint generated by default as identity primary key,
  version text not null unique,
  html text not null,
  is_active boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.app_versions enable row level security;
create index if not exists app_versions_active_idx on public.app_versions (is_active) where is_active = true;
